baseURL = 'https://blog.deshwal.in/'
languageCode = 'en-us'
title = 'Anubhav Deshwal'
theme = "papermod"

[menu]
  [[menu.main]]
    identifier = "Projects"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Projects"
    url = "/projects/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1